cargo-features = ["different-binary-name"]

[package]
name = "bro-run"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "bro-run"
filename = "bro"
path = "src/main.rs"
